In [103]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

In [ ]:
path = '/content/drive/MyDrive/DATASET/dataset and all/test_set_features.csv'
df_test = pd.read_csv(path)


In [105]:
df_test['age_group'] = df_test['age_group'].replace({'18 - 34 Years': 1, '35 - 44 Years': 2, '45 - 54 Years': 3,'55 - 64 Years':4,'65+ Years':5})
df_test['education']  = df_test['education'].replace({'< 12 Years': 1, '12 Years': 2, 'Some College': 3,'College Graduate':4})
df_test['income_poverty'] = df_test['income_poverty'].replace({'<= $75,000, Above Poverty':3,'> $75,000':2,'Below Poverty':1})

In [106]:
cols_to_use  = ['respondent_id', 'xyz_concern', 'xyz_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'health_insurance', 'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
       'education', 'income_poverty',
       'household_adults', 'household_children',
      ]
df_test1 = df_test[cols_to_use]

In [ ]:
ordinal_features = [
    'xyz_concern',
    'xyz_knowledge',
    'opinion_xyz_vacc_effective',
    'opinion_xyz_risk',
    'opinion_xyz_sick_from_vacc',
    'opinion_seas_vacc_effective',
    'opinion_seas_risk',
    'opinion_seas_sick_from_vacc',
    'age_group',
    'income_poverty','education'
]
for var in ordinal_features:
    median = df_test1[var].median()
    df_test1[var].fillna(median, inplace=True)



In [ ]:
binary_variables = [
    'behavioral_antiviral_meds', 'behavioral_avoidance', 'behavioral_face_mask',
    'behavioral_wash_hands', 'behavioral_large_gatherings', 'behavioral_outside_home',
    'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal', 'chronic_med_condition',
    'child_under_6_months', 'health_worker', 'health_insurance',
    'household_adults', 'household_children'
]
for var in binary_variables:
    mode = df_test1[var].mode()[0]
    df_test1[var].fillna(mode, inplace=True)



In [ ]:
df_test1.isnull().sum()

In [115]:
df_test3 = pd.get_dummies(df_test1, drop_first=True)

In [116]:
X_test21 = df_test3.drop(columns=['respondent_id'])

In [65]:
train = '/content/drive/MyDrive/DATASET/dataset and all/training_set_features.csv'
df  = pd.read_csv(train)

In [66]:
train_out = '/content/drive/MyDrive/DATASET/dataset and all/training_set_labels.csv'
df1 = pd.read_csv(train_out)

In [67]:
df2 = pd.concat([df, df1], axis=1)

In [117]:
df2['age_group'] = df2['age_group'].replace({'18 - 34 Years': 1, '35 - 44 Years': 2, '45 - 54 Years': 3,'55 - 64 Years':4,'65+ Years':5})
df2['education']  = df2['education'].replace({'< 12 Years': 1, '12 Years': 2, 'Some College': 3,'College Graduate':4})
df2['income_poverty'] = df2['income_poverty'].replace({'<= $75,000, Above Poverty':3,'> $75,000':2,'Below Poverty':1})

In [118]:
cols_to_use  = ['respondent_id', 'xyz_concern', 'xyz_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'health_insurance', 'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
       'education', 'income_poverty',
       'household_adults', 'household_children',
      'xyz_vaccine',
       'seasonal_vaccine']
df3 = df2[cols_to_use]


In [ ]:
ordinal_features = [
    'xyz_concern',
    'xyz_knowledge',
    'opinion_xyz_vacc_effective',
    'opinion_xyz_risk',
    'opinion_xyz_sick_from_vacc',
    'opinion_seas_vacc_effective',
    'opinion_seas_risk',
    'opinion_seas_sick_from_vacc',
    'age_group',
    'income_poverty','education'
]
for var in ordinal_features:
    median = df_test1[var].median()
    df3[var].fillna(median, inplace=True)


In [ ]:
binary_variables = [
    'behavioral_antiviral_meds', 'behavioral_avoidance', 'behavioral_face_mask',
    'behavioral_wash_hands', 'behavioral_large_gatherings', 'behavioral_outside_home',
    'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal', 'chronic_med_condition',
    'child_under_6_months', 'health_worker', 'health_insurance',
    'household_adults', 'household_children'
]
for var in binary_variables:
    mode = df_test1[var].mode()[0]
    df3[var].fillna(mode, inplace=True)

In [131]:
df3.isnull().sum()

respondent_id                  0
respondent_id                  0
xyz_concern                    0
xyz_knowledge                  0
behavioral_antiviral_meds      0
behavioral_avoidance           0
behavioral_face_mask           0
behavioral_wash_hands          0
behavioral_large_gatherings    0
behavioral_outside_home        0
behavioral_touch_face          0
doctor_recc_xyz                0
doctor_recc_seasonal           0
chronic_med_condition          0
child_under_6_months           0
health_worker                  0
health_insurance               0
opinion_xyz_vacc_effective     0
opinion_xyz_risk               0
opinion_xyz_sick_from_vacc     0
opinion_seas_vacc_effective    0
opinion_seas_risk              0
opinion_seas_sick_from_vacc    0
age_group                      0
education                      0
income_poverty                 0
household_adults               0
household_children             0
xyz_vaccine                    0
seasonal_vaccine               0
dtype: int

In [132]:
df5 = pd.get_dummies(df3, drop_first=True)

In [134]:
df5.isnull().sum()

respondent_id                  0
respondent_id                  0
xyz_concern                    0
xyz_knowledge                  0
behavioral_antiviral_meds      0
behavioral_avoidance           0
behavioral_face_mask           0
behavioral_wash_hands          0
behavioral_large_gatherings    0
behavioral_outside_home        0
behavioral_touch_face          0
doctor_recc_xyz                0
doctor_recc_seasonal           0
chronic_med_condition          0
child_under_6_months           0
health_worker                  0
health_insurance               0
opinion_xyz_vacc_effective     0
opinion_xyz_risk               0
opinion_xyz_sick_from_vacc     0
opinion_seas_vacc_effective    0
opinion_seas_risk              0
opinion_seas_sick_from_vacc    0
age_group                      0
education                      0
income_poverty                 0
household_adults               0
household_children             0
xyz_vaccine                    0
seasonal_vaccine               0
dtype: int

In [135]:
X = df5.drop(columns=['respondent_id', 'xyz_vaccine', 'seasonal_vaccine'])
y = df5[['xyz_vaccine', 'seasonal_vaccine']]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=7)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_train_scaled

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)
reg.score(X_test, y_test) # 0.38
reg.score(X_train, y_train) #0.36

In [ ]:
# SO I USED LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression().fit(X_train, y_train['xyz_vaccine'])
# log_reg.score(X_test, y_test['xyz_vaccine'])  0.82 so decent score

xyz_predictions = log_reg.predict_proba(X_test)[:,1]
print(xyz_predictions)

In [126]:
test_xyz = log_reg.predict_proba(X_test21)[:,1]
print(test_xyz)

[0.10228737 0.04539359 0.42023812 ... 0.14809559 0.05791805 0.62117282]


In [127]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression().fit(X_train, y_train['seasonal_vaccine'])


seasonal_predictions = log_reg.predict_proba(X_test)[:,1]
print(seasonal_predictions)

[0.8611303  0.04844359 0.3974929  ... 0.77015234 0.87502558 0.93014838]


In [128]:
test_seasonal = log_reg.predict_proba(X_test21)[:,1]
print(test_seasonal)

[0.28098402 0.04151242 0.72744196 ... 0.20736404 0.40173195 0.61549273]


In [129]:
roc_auc_xyz = roc_auc_score(y_test['xyz_vaccine'], xyz_predictions)
roc_auc_seasonal = roc_auc_score(y_test['seasonal_vaccine'], seasonal_predictions)
print(roc_auc_xyz)
print(roc_auc_seasonal)

0.8297113650030066
0.8432093989565003


In [142]:
final_1  = pd.DataFrame({'respondent_id': df_test1['respondent_id'], 'xyz_vaccine': test_xyz, 'seasonal_vaccine': test_seasonal})
final_1.to_csv('final_1.csv', index=False)